const dicionarioBotanico = {
  // 1. FLORES
  cor_petalas: {
    label: "Cor das Pétalas",
    opcoes: [
      { valor: "amarelo_palha", texto: "Amarelo-palha" },
      { valor: "amarelo_creme", texto: "Amarelo-creme" },
      { valor: "amarelo_limao", texto: "Amarelo-limão" },
      { valor: "amarelo_dourado", texto: "Amarelo-dourado" },
      { valor: "amarelo_ambar", texto: "Amarelo-âmbar" },
      { valor: "amarelo_mostarda", texto: "Amarelo-mostarda" },
      { valor: "laranja_pessego", texto: "Laranja-pêssego" },
      { valor: "laranja_claro", texto: "Laranja-claro" },
      { valor: "laranja_vivo", texto: "Laranja-vivo" },
      { valor: "laranja_cobre", texto: "Laranja-cobre" },
      { valor: "laranja_queimado", texto: "Laranja-queimado" },
      { valor: "vermelho_rosado", texto: "Vermelho-rosado" },
      { valor: "vermelho_cereja", texto: "Vermelho-cereja" },
      { valor: "vermelho_escarlate", texto: "Vermelho-escarlate" },
      { valor: "vermelho_carmim", texto: "Vermelho-carmim" },
      { valor: "vermelho_bordeaux", texto: "Vermelho-bordeaux" },
      { valor: "vermelho_enegrecido", texto: "Vermelho-enegrecido" },
      { valor: "rosa_bebe", texto: "Rosa-bebê" },
      { valor: "rosa_quartzo", texto: "Rosa-quartzo" },
      { valor: "rosa_chiclete", texto: "Rosa-chiclete" },
      { valor: "rosa_coral", texto: "Rosa-coral" },
      { valor: "rosa_pink", texto: "Rosa-pink" },
      { valor: "rosa_fucsia", texto: "Rosa-fúcsia" },
      { valor: "rosa_magenta", texto: "Rosa-magenta" },
      { valor: "lilas", texto: "Lilás" },
      { valor: "lavanda", texto: "Lavanda" },
      { valor: "violeta_claro", texto: "Violeta-claro" },
      { valor: "violeta_medio", texto: "Violeta-médio" },
      { valor: "violeta_intenso", texto: "Violeta-intenso" },
      { valor: "roxo_escuro", texto: "Roxo-escuro" },
      { valor: "roxo_enegrecido", texto: "Roxo-enegrecido" },
      { valor: "azul_celeste", texto: "Azul-celeste" },
      { valor: "azul_periwinkle", texto: "Azul-periwinkle" },
      { valor: "azul_medio", texto: "Azul-médio" },
      { valor: "azul_cobalto", texto: "Azul-cobalto" },
      { valor: "azul_indigo", texto: "Azul-índigo" },
      { valor: "verde_claro", texto: "Verde-claro" },
      { valor: "verde_menta", texto: "Verde-menta" },
      { valor: "verde_medio", texto: "Verde-médio" },
      { valor: "verde_escuro", texto: "Verde-escuro" },
      { valor: "branco_puro", texto: "Branco-puro" },
      { valor: "branco_creme", texto: "Branco-creme" },
      { valor: "branco_esverdeado", texto: "Branco-esverdeado" },
      { valor: "branco_rosado", texto: "Branco-rosado" },
      { valor: "bicolor_contrastante", texto: "Bicolor contrastante" },
      { valor: "degrade", texto: "Degradê (ombré)" },
      { valor: "manchada_pintalgada", texto: "Manchada / Pintalgada" },
      { valor: "listrada", texto: "Listrada" },
      { valor: "com_olho_central", texto: "Com olho central" },
    ],
  },
  formato_petala: {
    label: "Forma da Pétala",
    opcoes: [
      { valor: "arredondada", texto: "Arredondada" },
      { valor: "espatulada", texto: "Espatulada" },
      { valor: "lanceolada", texto: "Lanceolada" },
      { valor: "linear", texto: "Linear" },
      { valor: "fimbriada", texto: "Fimbriada / Franjada" },
      { valor: "ondulada", texto: "Ondulada" },
      { valor: "encurvada", texto: "Encurvada" },
      { valor: "reflexa", texto: "Reflexa" },
    ],
  },
  textura_petala: {
    label: "Textura da Pétala",
    opcoes: [
      { valor: "lisa", texto: "Lisa" },
      { valor: "velutinosa", texto: "Aveludada" },
      { valor: "cerosa", texto: "Cerosa" },
      { valor: "translucida", texto: "Translúcida" },
      { valor: "papilosa", texto: "Papilosa" },
    ],
  },
  numero_petalas: {
    label: "Número de Pétalas",
    opcoes: [
      { valor: "1_petala", texto: "1 pétala" },
      { valor: "3_petalas", texto: "3 pétalas (Trímera)" },
      { valor: "4_petalas", texto: "4 pétalas (Tetrâmera)" },
      { valor: "5_petalas", texto: "5 pétalas (Pentâmera)" },
      { valor: "6_petalas", texto: "6 pétalas" },
      { valor: "8_a_12_petalas", texto: "8 a 12 pétalas" },
      { valor: "13_a_21_petalas", texto: "13 a 21 pétalas" },
      { valor: "numerosas", texto: "Numerosas (> 21)" },
    ],
  },
  formato_geral_flor: {
    label: "Formato Geral (Corola)",
    opcoes: [
      { valor: "estrelada", texto: "Estrelada" },
      { valor: "tubular", texto: "Tubular" },
      { valor: "campanulada", texto: "Campanulada (Sino)" },
      { valor: "infundibuliforme", texto: "Infundibuliforme (Funil)" },
      { valor: "rotacea", texto: "Rotácea (Plana)" },
      { valor: "bilabial", texto: "Bilabial" },
      { valor: "papilionacea", texto: "Papilionácea (Borboleta)" },
      { valor: "em_espata", texto: "Em espata" },
      { valor: "ligulada", texto: "Ligulada (Fita)" },
      { valor: "capitular", texto: "Capitular (Cabeça)" },
    ],
  },
  simetria_floral: {
    label: "Simetria",
    opcoes: [
      { valor: "actinomorfa", texto: "Radial (Estrela)" },
      { valor: "zigomorfa", texto: "Bilateral" },
      { valor: "assimetrica", texto: "Assimétrica" },
    ],
  },
  inflorescencia: {
    label: "Inflorescência",
    opcoes: [
      { valor: "flor_solitaria", texto: "Solitária" },
      { valor: "racemo", texto: "Racemo" },
      { valor: "espiga", texto: "Espiga" },
      { valor: "umbela", texto: "Umbela" },
      { valor: "corimbo", texto: "Corimbo" },
      { valor: "cimeira", texto: "Cimeira" },
      { valor: "capitulo", texto: "Capítulo" },
      { valor: "cacho", texto: "Cacho (Panícula)" },
      { valor: "espata_espadice", texto: "Espata + Espádice" },
    ],
  },
  aroma_categoria: {
    label: "Categoria do Aroma",
    opcoes: [
      { valor: "inodora", texto: "Inodora" },
      { valor: "floral_doce", texto: "Floral-doce" },
      { valor: "citrico", texto: "Cítrico" },
      { valor: "especiado", texto: "Especiado" },
      { valor: "frutal", texto: "Frutal" },
      { valor: "mel_nectar", texto: "Mel / Néctar" },
      { valor: "fresco_verde", texto: "Fresco / Verde" },
      { valor: "almiscarado", texto: "Almiscarado" },
      { valor: "desagradavel", texto: "Desagradável" },
    ],
  },

  // 2. FOLHAS
  estrutura_folha: {
    label: "Estrutura da Folha",
    opcoes: [
      { valor: "simples", texto: "Simples" },
      { valor: "composta_imparipinada", texto: "Composta Imparipinada" },
      { valor: "composta_paripinada", texto: "Composta Paripinada" },
      { valor: "bipinada", texto: "Bipinada" },
      { valor: "palmada", texto: "Palmada" },
      { valor: "trifoliada", texto: "Trifoliada" },
    ],
  },
  cor_folha: {
    label: "Cor da Folha",
    opcoes: [
      { valor: "verde_claro", texto: "Verde-claro" },
      { valor: "verde_medio", texto: "Verde-médio" },
      { valor: "verde_escuro", texto: "Verde-escuro" },
      { valor: "verde_azulado", texto: "Verde-azulado" },
      { valor: "variegada", texto: "Variegada" },
      { valor: "avermelhada_roxa", texto: "Avermelhada / Roxa" },
      { valor: "cinza_prateada", texto: "Cinza / Prateada" },
    ],
  },

  // 3. CAULE
  tipo_caule: {
    label: "Tipo de Caule",
    opcoes: [
      { valor: "herbaceo", texto: "Herbáceo" },
      { valor: "sublenhoso", texto: "Sublenhoso" },
      { valor: "lenhoso_arbusto", texto: "Lenhoso (Arbusto)" },
      { valor: "lenhoso_arvore", texto: "Lenhoso (Árvore)" },
      { valor: "suculento", texto: "Suculento" },
      { valor: "trepador", texto: "Trepador" },
      { valor: "rizomatoso", texto: "Rizomatoso" },
      { valor: "bulboso", texto: "Bulboso" },
    ],
  },

  // 5. CARACTERÍSTICAS GERAIS
  porte: {
    label: "Porte da Planta",
    opcoes: [
      { valor: "miniatura", texto: "Até 15 cm" },
      { valor: "rasteira", texto: "15 a 40 cm" },
      { valor: "media", texto: "40 cm a 1 m" },
      { valor: "alta", texto: "1 a 2 m" },
      { valor: "arbustiva", texto: "1 a 3 m" },
      { valor: "arborea", texto: "Acima de 3 m" },
    ],
  },
  ciclo_vida: {
    label: "Ciclo de Vida",
    opcoes: [
      { valor: "anual", texto: "Anual" },
      { valor: "bienal", texto: "Bienal" },
      { valor: "perene", texto: "Perene" },
      { valor: "geofita", texto: "Geófita (Bulbo/Rizoma)" },
    ],
  },
};
